services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # env_file:
    #  - ./server/.env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo:latest
    ports:
      - "3030:27017"
    environment:
      - MONGO_LOG_LEVEL=crit
    volumes:
      - mongo_data:/data/db
  
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test-stage


volumes:
  mongo_data: