services:
  feed:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4343:4343
    env_file:
     - ./server/.env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - my-network

  mongo:
    image: mongo:jammy
    ports:
      - "3030:27017"
    environment:
      - MONGO_LOG_LEVEL=crit
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network
  
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test-stage


volumes:
  mongo_data:

networks:
  my-network:
    name: my-network
    external: true